### ISSUE TITLE
Use http.StatusBadRequest

### ISSUE THREAD

**Issue by mmlb** [mistifyio/mistify-agent#33]
Not dead set on it, 400 is pretty well known. Kind of wanted to try out the commenting feature also.

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|341ceab00198522f8eadeb5217b73fb86d34487e|[rpc/client.go#L45](https://github.com/mistifyio/mistify-agent/blob/341ceab00198522f8eadeb5217b73fb86d34487e/rpc/client.go#L45)| #32 |[![#32](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/mistifyio/mistify-agent/pull/32)|

**Comment by TauZero** [comment]
I usually use the http.Status ones, forgot this time. Fixed.
