### ISSUE TITLE
No need to `new` the buffer

### ISSUE THREAD

**Issue by mmlb** [mistifyio/mistify-agent#34]
From docs `The zero value for Buffer is an empty buffer ready to use.`

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|341ceab00198522f8eadeb5217b73fb86d34487e|[rpc/client.go#L46](https://github.com/mistifyio/mistify-agent/blob/341ceab00198522f8eadeb5217b73fb86d34487e/rpc/client.go#L46)| #32 |[![#32](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/mistifyio/mistify-agent/pull/32)|

**Comment by TauZero** [comment]
Fixed
